### PR TITLE
Support openatv margins

### PR DESCRIPTION
**Pull request by GhostofGeeeee**
- Fix typo
- Support openatv margins(margin_before, zap_margin_before, margin_after, zap_margin_after) as default on editor fix(https://github.com/oe-alliance/enigma2-plugins/issues/625)
- Support openatv zap_has_endtime

### CODE REVIEW

**Comment by jbleyel** [comment]
Looks good to me.
But I haven’t tested this.
Have you do a regression test?

**Comment by GhostofGeeeee** [comment]
> Have you done a regression test?

Good Question! Maybe I lost this fix(2nd commit).
Now the final [commit](https://github.com/oe-alliance/enigma2-plugins/commit/a0f19b3c36e4e44daee910cbfb054982f3ff5f7c) on branch AutoTimer2(https://github.com/GhostofGeeeee/enigma2-plugins/tree/AutoTimer2)
Thank you

**Comment by GhostofGeeeee** [comment]
Can you please have a look to another Issue described here https://github.com/GhostofGeeeee/enigma2-plugins/commit/2cd6721de8bc0135bb752f98c52b329264b11e93.

**Comment by jbleyel** [comment]
> Can you please have a look to another Issue described here [GhostofGeeeee@2cd6721](https://github.com/GhostofGeeeee/enigma2-plugins/commit/2cd6721de8bc0135bb752f98c52b329264b11e93).

Check my comments.

**Comment by jbleyel** [comment]
Is this pull ready for merge?

**Comment by GhostofGeeeee** [comment]
> Is this pull ready for merge?

You can use this [commit](https://github.com/oe-alliance/enigma2-plugins/commit/833e6b676f10b70ed9c6da926523140dbfdd74bc) on branch AutoTimer3(https://github.com/GhostofGeeeee/enigma2-plugins/tree/AutoTimer3)

**Comment by GhostofGeeeee** [comment]
> Is this pull ready for merge?

You can use this [commit](https://github.com/oe-alliance/enigma2-plugins/commit/833e6b676f10b70ed9c6da926523140dbfdd74bc) on branch AutoTimer3(https://github.com/GhostofGeeeee/enigma2-plugins/tree/AutoTimer3)
or merge, yes!

**Pull request merged**
