### PR TITLE
Fix for #337

### PR DESCRIPTION
**Pull request by markuschen**
Fix for https://github.com/oe-alliance/enigma2-plugins/issues/337

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
I believe this is the wrong approach.
Anything already mounted on /media/hdd will be hidden.
Having a NAS as recording location doesn't mean there is no USB stick on the box for picons, configs and backups.

**Comment by markuschen** [comment]
But this is exactly the intention in "original" (not autofs) hdd_replacement handling, see line 307 in AutoMount.py:
So why should autofs not work the same as the original behavior?

**Comment by Schimmelreiter** [comment]
In that case, the original behaviour is also silly :)
I think in that case, the mount-helper would be a better place to fix hdd replacement (By simply checking for it and not using /media/hdd itself).

**Comment by Schimmelreiter** [comment]
The bind mount here is correct ... but it's silly nothing gets done against other media getting mounted there in the first place.

**Comment by nickersk** [comment]
no action over 2 yrs. closing.

**Pull request closed without merging**
