### PR TITLE
If we get this far and either of extdesc1 or extdesc2 does not exist,…

### PR DESCRIPTION
**Pull request by original-birdman**
… set retValue based on whether they are the same, so that two empty values (whch are equal) return True.

### CODE REVIEW

**Review by Grumpy-Geoff — COMMENTED** [review]
Timers don't have an extended description, so for the case where a title and short description match, a completed timer should prevent a new timer being generated.
The current code fails in this regard. My attempt at pseudo-code of the problem below -
```
            if "Check for uniqueness in" is "Title and all descriptions", then
                if both extended descriptions are present, then  (*** which can't be true for timers)
                    if the extended descriptions are greater than a 70% match, then
                        decision -- don't create a new timer
                    else 
                        decision -- do create a new timer
                    end-if
                end-if  #### this is the problem if either extended description is not present, no decision is made to NOT create (i.e. default "creation" position is left)

```
I think your new code still has the bug that manifests when comparing the EPG event and an existing timer.
I think the code should assign `retValue = True` before evaluating the non-null values of extdesc1 and extdesc2, and also get rid of the else clause on `if timer.searchForDuplicateDescription == 2:`
thus -
```
					foundShort = (0.7 < SequenceMatcher(lambda x: x == " ", shortdesc1, shortdesc2).ratio())
					if foundShort:
						retValue = True   ### relocate else clause to here ###							
						if timer.searchForDuplicateDescription == 2:
							if extdesc1 and extdesc2:
								# Some channels indicate replays in the extended descriptions
								# If the similarity percent is higher then 0.7 it is a very close match
								retValue = (0.7 < SequenceMatcher(lambda x: x == " ", extdesc1, extdesc2).ratio())
```

**Comment by original-birdman** [comment]
> Timers don't have an extended description

I hadn't considered that, thanks.
I'll check the rest shortly...

**Comment by original-birdman** [comment]
Hang on...

If timers don't have an extended description then what does the `rtimer.extdesc` field contain?
And given that `checkSimilarity()` is always called with at least _one_ timer (the one it's wondering whether to create) why not just abandon this test completely as the field doesn't exist?
Then remove the "all descriptions" option from the config too.

**Comment by Grumpy-Geoff** [comment]
> If timers don't have an extended description then what does the `rtimer.extdesc` field contain?

A null.



> And given that `checkSimilarity()` is always called with at least _one_ timer (the one it's wondering whether to create)

Nope, an EPG entry



> why not just abandon this test completely as the field doesn't exist?
> Then remove the "all descriptions" option from the config too.

It can be a check on existing recordings too, which can have extended descriptions.

**Comment by original-birdman** [comment]
OK, then you suggestion would be the way to go.

I'll code it up and check it for the case I have which was causing me to see the problem, then submit another PR - should be later today.

**Comment by original-birdman** [comment]
New PR at:
https://github.com/oe-alliance/enigma2-plugins/pull/501

**Pull request closed without merging**
