### PR TITLE
EPG Search: Add optional orbital position to search list

### PR DESCRIPTION
**Pull request by prl001**
Optionally add an orbital position to each search result.

Code cleanup to simplify `EPGSearchList`.

Allow AutoTimer icons to be displayed if `EPGList` supports their display.

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
Being quite happy with your enhancements, I'm not that happy withthe lay-out of the screen "EPGSelection" in a 1080 skin.
As you can see there is an enormous gap between the time and the orbit-position:
epg_s-02
or the service/event:
epg_s-03
Is there anything I can do about that in the skin-screen?

**Comment by prl001** [comment]
The gap is largely due to the width set aside for, but not completely used by, the dd/mm, HH:MM field in the `EPGList` component (with `self.type == EPG_TYPE_SINGLE`) in the host image. This width is simply copied by `EPGSearchList` (both with my changes and without them). You can verify this by looking at the layout for the single channel EPG (on the Beyonwiz I can view that from the popup menu on long-EPG or long-INFO, YMMV).

Some of the gap is also from the fact that the date/time field is left aligned and the orbital position is right aligned.

The calculation of the date/time field width has not changed in the new version of EPG Search, and the gap you see without the orbital position displayed is the same as the gap was in the previous version of the plugin.

The short form day name field is, I suspect, far wider than it needs to be in any locale, too.

Because the day name date/time field width calculation is in `EPGList.buildSingleEntry()`, I suggest that it should be fixed there.

These fields are also too wide in the Beyonwiz image, and I intend to clean them up in `EPGList` as soon as peteru has finished his mammoth merge from upstream and has resumed accepting pull requests.

I gave [suggested field widths](https://github.com/oe-alliance/enigma2-plugins/issues/86#issuecomment-231935104) for these fields in earlier discussion: 8% of the list width for the day name and 20% of the list width for the date/time. The current VIX code for those two fields uses 10% and 25% respectively.

The relevant lines of code are 594 and 595 in the current VIX version of [EPGList.py](https://github.com/OpenViX/enigma2/blob/master/lib/python/Components/EpgList.py).

And yes, it would be nice if these widths could be skinned, but EPGList is a large and complicated class (~1700 lines of code), some of the EPG screen displays (like the EPG grid) are not amenable to changing to TemplatedMultiContent, and changes in it would need to be reflected in all the images.

**Comment by RobvanderDoes** [comment]
> I gave suggested field widths for these fields in earlier discussion: 8% of the list width for the day name and 20% of the list width for the date/time. The current VIX code for those two fields uses 10% and 25% respectively.
> 
> The relevant lines of code are 594 and 595 in the current VIX version of EPGList.py.
> 

I've taken that advise on board and it looks good. But: only as long as no orbital postion has been chosen; as soon as that is the case the gap between end-time and orbit-pos is huge again.

**Comment by prl001** [comment]
That looks like a wider list width than the 660 px example I looked at. The problem is basically trying to accommodate all the different list widths that are around. My EPGSearch code allows 17% of the list width for the orbital position - 14% for the orbital data itself and an 3% gap on the right, between the orbital position and the title, to allow for the fact that the orbital position is right aligned and the title is left aligned.

**Comment by prl001** [comment]
Here's my 660 px mock-up again using my suggested 8%, 20%, 14+3% for the first three columns. In the first screenshot, I've highlighted the orbital position field in green so that its width is clear.

If orbital positions are to be allowed to be 100 degrees or larger, I don't think the orbital position column can be made a lot narrower and still allow for variations in text width due to different fonts. I presume that for Western European users, satellite positions aren't often going to be 100deg or bigger; that would put them too near, or below, the horizon, but I think the generality should be kept.

The space between the orbital position and the title could be reduced a bit, but I don't think that's the gap that's causing concern. That gap is smaller than the maximum gap I see between the day name and the date (when the date is "Fri" in English-language locales).

Because the calculation is percentage-based, these gaps will be wider when the list space is wider, but there's not much room left for adjustment if the list is to work at 660 px and allow for satellite positions in the 100-180E/W range.

orbpos660-highlight

orbpos660

**Comment by RobvanderDoes** [comment]
> Here's my 660 px mock-up again using my suggested 8%, 20%, 14+3% for the first three columns.

For ViX I've been able to correct the first two columns (the lines 594 & 595 in EpgList.py you pointed out, set to 8% & 19%; this suits al the skins I've tested), but the rest is above my head. So once the orbital position is active, there's again the huge gap between the end time and the orbitpos.

**Comment by RobvanderDoes** [comment]
In other words: I don't know which entry of EpgList.py is used by the orbital position, but it seems to be fixed by lines 109 and beyond of EPGSearch.py. If that's correct, that would give little options for adapting per distro.

**Comment by prl001** [comment]
The row layout for `EPGList` is part done in `EPGList` and partly in `EPGSearchList`.

The layout of the non-optional columns is set in `EPGList.recalcEntrySize()` lines 594-596 in the VIX source (but you've probably already found that). There, the widths are laid out as a percentage of the list width.

Then, in `EPGSearchList.buildEPGSearchEntry()`, lines 109 and following "steal" some of the space in `self.descr_rect`, the space for the event title. The orbital position element is inserted at `self.descr_rect.x` with width `orbitalPosWidth`. The left edge of the title is moved to `self.descr_rect.x + orbitalPosWidth + orbitalPosSpace`, and its width is set to use the rest of the row. The orbital position widths are currently done as 

Later, in lines 129-134, the title box is reduced by a little more than the space used by any timer icons.

It is possible to independently make the width of the orbital position box depend on the font size instead of a fixed percentage. It's about 2 extra lines of code, and two modified lines.

In both `EPGList` and `EPGSearchList`, you could set a font-size dependent width by doing something like:

    someFieldWidth = someNumber * (self.eventFontSizeSingle + config.epgselection.enhanced_eventfs.value)

But doing that only in `EPGSearchList` doesn't solve the problem of trying to improve the layout of `EPGList` and `EPGSearchList`.

If you want tight, clean columns in a percentage-based system, that is very fragile to the user increasing the single channel EPG font size (long-EPG>Show EPG for current channel, MENU>Event font size). With my 660 px example and the "tight" percentages for the EPGSearch columns (8%, 20%, 14+3%), just increasing the event font size by 3 points causes the date/time field to overflow, the day name field to just overflow on Wednesdays (English-language locale) and the orbital position field to nearly overflow.

In the Beyonwiz image, the `MovieList` code already does font-size based field width calculation (line 450 of Movielist.py in the Beyonwiz source).

In the VIX image, the skin is given a "date field width" attribute to compensate for changes in the skin font size (lines 307-308, 345 & 438-439 in the VIX source). That is also vulnerable to the user changing the `MovieList`/`MovieSelection` font size setting.

**Pull request merged**
