### PR TITLE
Pass on all incoming parameters on intercepted calls.

### PR DESCRIPTION
**Pull request by original-birdman**
Simplify arg counting code.

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
There is a merge conflict.

**Comment by original-birdman** [comment]
There wasn't when I created it....but I did update the version in a file that was updated by one of the others.
I'll make another....

**Comment by AbuBaniaz** [comment]
Please note the comments about removal of python 3 code.

**Comment by original-birdman** [comment]
The python3 bits are in the dev branch, not here.
This does test for python3 at the start, though, but in a simpler way.

**Comment by jbleyel** [comment]
@ALL / I prefer commits to master and dev if the code is PY2 and PY3 compatible. This will reduce merge conflicts in dev branche.

**Comment by original-birdman** [comment]
But the idea was to get the production version fixed first, as it can produce a crash.
Now that's out of the way I can make the same changes to `Modifications.py` for dev.

**Comment by AbuBaniaz** [comment]
The python 3 bits are there. Prl added them, I committed them. That is 4 times now it has been mentioned. Are we on different pages?

You are reading the term `dev` literally. Different images build from different branches . So both branches are `production` Please leave the python 3 compatibility code in.

**Comment by AbuBaniaz** [comment]
The python 3 compatibility code was added here:
https://github.com/oe-alliance/enigma2-plugins/commit/d6c0614d4800e21eaa1217f7f6813914991393e2

**Comment by original-birdman** [comment]
None of that has been removed.
The Py3 test has been simplified. (although the rest of the code doesn't actually have Py3 changes - such as the absolute imports).

**Comment by original-birdman** [comment]
I'm now working on the PR for the dev branch.
That is where `Modifications.py` **does** have Py3 changes, _e.g._ for imports.

**Comment by original-birdman** [comment]
As it turns out the PR _would_ have applied to dev as well (patch applied the diff with a 1 line offset throughout).
But I'm submitting a dev-specific one now...

**Pull request closed without merging**
