### PR TITLE
[partnerbox]: Fix serversocket import

### PR DESCRIPTION
**Pull request by Hains**

### CODE REVIEW

**Comment by jbleyel** [comment]
Braucht man den Import überhaupt?

**Comment by Hains** [comment]
I have problems with DreamBoxedit and OpenATV. I've set set password and can FTP to box with ssh only.
So i can't test partnerbox without 'serversocket import' properly yet.
Box is Uclan ustym4kpro. Fresh flash with OpenATV 6.5.

**Comment by jbleyel** [comment]
I don't find the usage of serversocket inside of the plugin.

**Comment by jbleyel** [comment]
It looks like an old import and no longer used.

**Comment by Hains** [comment]
Indeed, it can be removed.
I'll close PR and create new one

**Pull request closed without merging**
