### PR TITLE
[imdb] Include trailing slash in find URL

### PR DESCRIPTION
**Pull request by adoxa**
This prevents the 308 redirect message.

### CODE REVIEW

**Comment by adoxa** [comment]
Don't commit yet, it seems to have broken a single search result.

**Comment by jbleyel** [comment]
You can check this :
https://github.com/opendreambox/enigma2-plugins/tree/master/imdb

**Comment by adoxa** [comment]
I did something similar (pass the link directly to `IMDBquery2`), but haven't tested it, yet.

**Comment by adoxa** [comment]
It works. However, what it found is not what I expected it to find, so I'll look into that, now...

**Comment by adoxa** [comment]
The link might be 8 digits. All good now.

**Pull request merged**
