### PR TITLE
Update pot and po files

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by jbleyel** [comment]
I think you have damaged something.

Cloning into 'enigma2-plugins'...
remote: Enumerating objects: 63373, done.
remote: Counting objects: 100% (3923/3923), done.
remote: Compressing objects: 100% (3318/3318), done.
remote: Total 63373 (delta 2217), reused 1135 (delta 596), pack-reused 59450
Receiving objects: 100% (63373/63373), 45.01 MiB | 6.13 MiB/s, done.
Resolving deltas: 100% (44128/44128), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  '3dsettings/po/3DSettings.pot'
  '3dsettings/po/3dsettings.pot'
  'shoutcast/po/SHOUTcast.pot'
  'shoutcast/po/shoutcast.pot'
  
  
  
  same for python3

**Comment by persianpros** [comment]
You're using windows right?

That's windows problem, you need to remove old

3dsettings.pot
shoutcast.pot

from git as new ones using correct cases, I can do it if you want.

**Comment by jbleyel** [comment]
i have removed the duplicate files

**Comment by jbleyel** [comment]
Please change the name to the correct case.

**Comment by jbleyel** [comment]
I think the correct names are:
3dsettings.pot
shoutcast.pot

and not
SHOUTcast.pot
3DSettings.pot

**Pull request merged**
