### PR TITLE
If the config file fails to parse (corrupt, or empty) then ignore it.

### PR DESCRIPTION
**Pull request by original-birdman**

### CODE REVIEW

**Comment by jbleyel** [comment]
better solution imho.

https://github.com/oe-alliance/enigma2-plugins/commit/acba9d01b3b06e2df77fc4aedc43abeaebf08bc7

**Comment by original-birdman** [comment]
> better solution imho.

Except for the pop-up message.....

**Comment by jbleyel** [comment]
Why do you not want to notify the user?

**Comment by original-birdman** [comment]
> Why do you not want to notify the user?

That's not the issue. See the comment on the "fix" messages.

**Pull request closed without merging**
