### PR TITLE
Pass on all incoming parameters on intercepted calls.

### PR DESCRIPTION
**Pull request by original-birdman**
Simplify arg counting code.
Bump version to 1.31.

### CODE REVIEW

**Comment by original-birdman** [comment]
OK. What about this one having no conflicts?

**Comment by original-birdman** [comment]
NOTE: This will not merge into dev, only master.
I'll do another one for dev with the same/equiv changes.

**Comment by jbleyel** [comment]
WHY?

**Comment by original-birdman** [comment]
TO PREVENT A CRASH!

**Comment by jbleyel** [comment]
I'm talking about "another one"!
Why not using the same commit for dev.

**Comment by original-birdman** [comment]
Because the dev code has Py3 (and other) changes to it and the patch probably won't take.
So I'll do it by hand.

**Comment by AbuBaniaz** [comment]
I have picked the other two commits to dev branch already.

**Pull request merged**
