### PR TITLE
Change strings that contain '/n' to '\n'

### PR DESCRIPTION
**Pull request by mapi68**

### CODE REVIEW

**Comment by jbleyel** [comment]
That’s strange because this is /n for years and now it’s wrong? Can you explain why you wanna change this?

**Comment by mapi68** [comment]
Command for new line is \n, 
https://github.com/oe-alliance/enigma2-plugins/issues/641

**Comment by jbleyel** [comment]
You have only changed the it.po and this will not fix your issue

**Comment by jbleyel** [comment]
The problem is inside of the MPHelp Plugin.

**Comment by jbleyel** [comment]
You need to add it.po for MPHelp plugin.

https://github.com/oe-alliance/enigma2-plugins/tree/master/mphelp/po

**Pull request closed without merging**
