### PR TITLE
Update plugin.py

### PR DESCRIPTION
**Pull request by Belfagor2005**
Force remove b' from lenght

### CODE REVIEW

**Comment by jbleyel** [comment]
Is this change also working for python2?

**Comment by Belfagor2005** [comment]
yes, why shouldn't it, it's a python command
Regars my friend ;)

**Comment by Belfagor2005** [comment]
ah  .. no, i have atv 7.0 on dinobot 4k mini
sorry

**Comment by Belfagor2005** [comment]
Try this and Lyrics is ok Now 
when you press Info on the player or on a song
before it crashed, it didn't work
this is a personal modification, externally skinned fhd . hd and sd..
Screenshot 2022-11-17 at 20-48-33 Vivant DINOBOT 4K mini - OpenWebif
[MerlinMusicPlayerOklLyrics.zip](https://github.com/oe-alliance/enigma2-plugins/files/10035051/MerlinMusicPlayerOklLyrics.zip)

**Pull request merged**
