### PR TITLE
Having got that far, assume similarity check is True unless both Exte…

### PR DESCRIPTION
**Pull request by original-birdman**
…nded Descriptions are present.

### CODE REVIEW

**Comment by Huevos** [comment]
`retValue = True` why not do that on line #891 and do away with the other else clause?

**Comment by jbleyel** [comment]
You can optimize the whole function and you only need retValue as variable.

**Comment by original-birdman** [comment]
> You can optimize the whole function and you only need retValue as variable.

Indeed, but this was a simple fix for a specific (seen) problem and rewriting a function completely can end up with comments about "why rewrite it rather than just supply a simple fix".
I'm quite happy to rewrite it.

**Comment by original-birdman** [comment]
So how about this?
```
# Once we've failed in checkSimilarity() we've failed
# So just keep testing while retValue is True
# 
        def checkSimilarity(self, timer, name1, name2, shortdesc1, shortdesc2, extdesc1, extdesc2, force=False):
                if name1 and name2:
                        retValue = (0.8 < SequenceMatcher(lambda x: x == " ", name1, name2).ratio())
                else:   # Assume no match unless *both* are there
                        retValue = False
                if retValue:
                        # If one (or both) of shortdesc1 and shortdesc2 is blank/(None?) use a straight compare
                        # to make it True if both are blank, but False otherwise
                        if not (shortdesc1 and shortdesc2):
                                retValue = (shortdesc1 == shortdesc2)
                        elif (timer.searchForDuplicateDescription > 0) or force:
                                # If the similarity percent is higher then 0.7 it is a very close match            
                                retValue = (0.7 < SequenceMatcher(lambda x: x == " ", shortdesc1, shortdesc2).ratio())
                                # Only check Extended Descriptions (when asked) if both are present
                                if retValue and (timer.searchForDuplicateDescription == 2) and (extdesc1 and extdesc2):
                                        # Some channels indicate replays in the extended descriptions
                                        # If the similarity percent is higher then 0.7 it is a very close match
                                        retValue = (0.7 < SequenceMatcher(lambda x: x == " ", extdesc1, extdesc2).ratio())
                return retValue
```

**Comment by Grumpy-Geoff** [comment]
```
>         if retValue:
>                 # If one (or both) of shortdesc1 and shortdesc2 is blank/(None?) use a straight compare
>                 # to make it True if both are blank, but False otherwise
>                 if not (shortdesc1 and shortdesc2):
>                         retValue = (shortdesc1 == shortdesc2)
```

I don't think that's correct as you're comparing shortdesc1 and shortdesc2 even though it may be a title-only check.

I'm not a python coder, but I think a simplified version is something like this -
```
        def checkSimilarity(self, timer, name1, name2, shortdesc1, shortdesc2, extdesc1, extdesc2, force=False):
                retValue = False
                if name1 and name2:
                        if 0.8 < SequenceMatcher(lambda x: x == " ", name1, name2).ratio():
		                # NOTE: only check extended & short if title is a partial match
                        	if timer.searchForDuplicateDescription > 0 or force:
	                                # If the similarity percent is higher then 0.7 it is a very close match
	                                if shortdesc1 and shortdesc2 and (0.7 < SequenceMatcher(lambda x: x == " ", shortdesc1, shortdesc2).ratio()):
                                                retValue = True  # short descriptions are similar
                                                if timer.searchForDuplicateDescription == 2 and extdesc1 and extdesc2:
                                                        # Some channels indicate replays in the extended descriptions
                                                        # If the similarity percent is higher then 0.7 it is a very close match
                                                        retValue = (0.7 < SequenceMatcher(lambda x: x == " ", extdesc1, extdesc2).ratio())
                        	else:
                        	        retValue = True
                return retValue

```

**Comment by original-birdman** [comment]
> I don't think that's correct as you're comparing shortdesc1 and shortdesc2 even though it may be a title-only check.

There *are* no title-only checks.
All checks are done once all of the details are known for both sides of the check.

**Comment by Grumpy-Geoff** [comment]
> There _are_ no title-only checks.

Huh?
"Check for uniqueness in" ==> Title, is attribute searchForDuplicateDescription = "0"

**Comment by jbleyel** [comment]
How about this?


```
	def checkSimilarity(self, timer, name1, name2, shortdesc1, shortdesc2, extdesc1, extdesc2, force=False):
		retValue = False
		if name1 and name2 and (0.8 < SequenceMatcher(lambda x: x == " ", name1, name2).ratio()):
			# NOTE: only check extended & short if tile is a partial match
			retValue = True
			if timer.searchForDuplicateDescription > 0 or force:
				retValue = False
				# If the similarity percent is higher then 0.7 it is a very close match
				if shortdesc1 and shortdesc2 and (0.7 < SequenceMatcher(lambda x: x == " ", shortdesc1, shortdesc2).ratio()):
					# At this point we assume the similarity match to be True
					# unless we have been asked to check Extended Descriptions
					# and we have *both* Extended Descriptions in place;
					# in which case we test them.
					retValue = True
					if timer.searchForDuplicateDescription == 2 and extdesc1 and extdesc2:
						# Some channels indicate replays in the extended descriptions
						# If the similarity percent is higher then 0.7 it is a very close match
						retValue = (0.7 < SequenceMatcher(lambda x: x == " ", extdesc1, extdesc2).ratio())
		return retValue

```

**Comment by original-birdman** [comment]
> There are no title-only checks

Sorry, I was thinking of calls rather than checks. Not sure why...

**Comment by original-birdman** [comment]
> jbleyel ...How about this?

That suffers (as does the existing code, actually) of saying that they are similar if one has a description and the other does not.

**Comment by original-birdman** [comment]
So, I'd suggest this, catering for a title-only check, and ensuring there are comments to explain what is happening.
```
# Once we've failed in checkSimilarity() we've failed
# So just keep testing while retValue is True
#
        def checkSimilarity(self, timer, name1, name2, shortdesc1, shortdesc2, extdesc1, extdesc2, force=False):
                if name1 and name2:
                        retValue = (0.8 < SequenceMatcher(lambda x: x == " ", name1, name2).ratio())
                else:   # Assume no match unless *both* have a value
                        retValue = False
                if retValue and ((timer.searchForDuplicateDescription > 0) or force):
                        # If one (or both) of shortdesc1 and shortdesc2 is blank/(None?) use a straight compare
                        # to make it True if both are blank, but False otherwise
                        if not (shortdesc1 and shortdesc2):
                                retValue = (shortdesc1 == shortdesc2)
                        else:
                                # If the similarity percent is higher then 0.7 it is a very close match
                                retValue = (0.7 < SequenceMatcher(lambda x: x == " ", shortdesc1, shortdesc2).ratio())
                                # Only check Extended Descriptions (when asked) if *both* are present
                                if retValue and (timer.searchForDuplicateDescription == 2) and (extdesc1 and extdesc2):
                                        # Some channels indicate replays in the extended descriptions
                                        # If the similarity percent is higher then 0.7 it is a very close match
                                        retValue = (0.7 < SequenceMatcher(lambda x: x == " ", extdesc1, extdesc2).ratio())
                return retValue
```

**Comment by jbleyel** [comment]
You should test the code .. maybe outside with demo data.

**Pull request merged**
