### PR TITLE
[Updated] Simplify and fix weather plugin icons rendering

### PR DESCRIPTION
**Pull request by DimitarCC**

### CODE REVIEW

**Comment by jbleyel** [comment]
Crash:


15:15:10.2673   File "/usr/lib/enigma2/python/Screens/Screen.py", line 141, in hide
15:15:10.2677   File "/usr/lib/enigma2/python/Components/Renderer/Renderer.py", line 14, in onHide
15:15:10.2680   File "/usr/lib/enigma2/python/Components/Element.py", line 67, in setSuspend
15:15:10.2683   File "/usr/lib/enigma2/python/Components/Renderer/MSNWeatherPixmap.py", line 45, in doSuspend
15:15:10.2686   File "/usr/lib/enigma2/python/Components/Renderer/MSNWeatherPixmap.py", line 66, in changed
15:15:10.2689   File "/usr/lib/enigma2/python/Components/Renderer/MSNWeatherPixmap.py", line 53, in updateIcon
15:15:10.2692   File "/usr/lib/enigma2/python/Tools/LoadPixmap.py", line 8, in LoadPixmap
15:15:10.2696 TypeError: 'NoneType' object is not subscriptable
15:15:10.2696 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xada1ff60>>,('SetupActions', 'menu')) failed)

**Comment by Huevos** [comment]
Is this crash in OpenATV?

**Comment by jbleyel** [comment]
Yes and in many other images.

**Comment by jbleyel** [comment]
LoadPixmap(None) -> Crash

**Comment by DimitarCC** [comment]
The question here is why it is None at first place. I guess incorrect path or missing icon...

Изпратено от Outlook за Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jbleyel** [comment]
> The question here is why it is None at first place. I guess incorrect path or missing icon... 


https://github.com/oe-alliance/enigma2-plugins/commit/ba57023190ec81e420913394fd7418bc35f3462e

**Comment by Huevos** [comment]
How will that work? Won't it just raise the exception?

https://github.com/openatv/enigma2/blob/master/lib/python/Tools/LoadPixmap.py#L28

**Comment by jbleyel** [comment]
It's only a workaround and quick fix to prevent the crash.
The code whole code needs a review but i will not do that.

**Comment by Huevos** [comment]
But it file name is empty it will crash.

**Comment by jbleyel** [comment]
> But it file name is empty it will crash.

Then you need to stop calling LoadPixmap if empty.

**Comment by Huevos** [comment]
The None call in the original code was to remove the icon.

**Comment by jbleyel** [comment]
> The None call in the original code was to remove the icon.

LoadPixmap(None) -> 


15:15:10.2692 File "/usr/lib/enigma2/python/Tools/LoadPixmap.py", line 8, in LoadPixmap
15:15:10.2696 TypeError: 'NoneType' object is not subscriptable

**Comment by jbleyel** [comment]
```
	def updateIcon(self, filename):
		new_IconFileName = filename
		if (self.iconFileName != new_IconFileName):
			self.iconFileName = new_IconFileName
			if self.iconFileName:
				self.pix = LoadPixmap(self.iconFileName)
				try:
					self.instance.setPixmapScale(BT_SCALE | BT_KEEP_ASPECT_RATIO)
				except:
					self.instance.setScale(1)
				self.instance.setPixmap(self.pix)
			else:
				self.instance.setPixmap(None)

```

**Pull request merged**
