### PR TITLE
Updated plugin.py

### PR DESCRIPTION
**Pull request by Orlandoxx**
Fixed date & time

### CODE REVIEW

**Comment by Huevos** [comment]
Did you try, ` c = time.strptime(item.observationtime, "%EX")`, which should use the locale's representation for HMS.

**Comment by Orlandoxx** [comment]
No, because what to use for HM then ? That try/except combo works, so be it. You can always change the solution, If you have a better one.

try:
						c = time.strptime(item.observationtime, "%H:%M:%S")
						self["observationtime"].text = _("Observation time: %s") % time.strftime("%H:%M", c)
					except:
						c = time.strptime(item.observationtime, "%H.%M.%S")
						self["observationtime"].text = _("Observation time: %s") % time.strftime("%H.%M", c)

**Comment by Huevos** [comment]
```
c = time.strptime(item.observationtime, "%EX")
self["observationtime"].text = _("Observation time: %s") % time.strftime("%EX", c)[:5]
```

**Comment by Orlandoxx** [comment]
With your patch, I get : **'E' is a bad directive in format '%EX'**
So can you merge my patch ?

**Comment by Huevos** [comment]
I think Birdman has added this confusion. That format is for linux function strptime.

**Comment by Orlandoxx** [comment]
OK, but I tested this:

  c = time.strptime(item.observationtime, "%X")
  self["observationtime"].text = _("Observation time: %s") % time.strftime("%X", c)[:5]

and this works. Would you like to change this or leave it ?

**Comment by Huevos** [comment]
Yes please update. Avoid try except.

**Comment by Orlandoxx** [comment]
Allright. I will make a new patch and a PR.

**Pull request merged**
